import Math115

-- Every line must contain only the three standard axioms allowed upstream:
-- propext, Classical.choice, Quot.sound.  A sorryAx is a verification failure.
#print axioms OAI.ContingencyTables.IntegerWeightedTransport.leafEnergySum_le_graphEnergy
#print axioms OAI.ContingencyTables.IntegerWeightedTransport.integer_root_graph_transport
#print axioms OAI.ContingencyTables.IntegerWeightedTransport.weightedFuture_upper_quadratic
#print axioms OAI.ContingencyTables.IntegerWeightedTransport.weightedFuture_upper_quarter
#print axioms OAI.ContingencyTables.IntegerWeightedTransport.correctionKernel_upper_quarter
#print axioms OAI.ContingencyTables.IntegerWeightedTransport.recursive_root_potential_quarter
#print axioms OAI.ContingencyTables.IntegerWeightedTransport.integer_root_leaf_transport_quarter
#print axioms OAI.ContingencyTables.IntegerWeightedTransport.integer_root_graph_transport_quarter
#print axioms OAI.ContingencyTables.IntegerWeightedTransport.recursive_root_potential_widths
#print axioms OAI.ContingencyTables.IntegerWeightedTransport.integer_root_leaf_transport_widths
#print axioms Math115.GlobalDisplayOwnership.edge_owner_unique_upstream

-- Actual ordinary-table incidence, shifted fibers, tails, and expectation.
#print axioms Math115.SmallEntrySwitching.all_donor_incidence_bound
#print axioms Math115.SmallEntrySwitching.donor_capacity_sum_lower
#print axioms Math115.SmallEntrySwitching.donor_capacity_sum_lower_of_margins
#print axioms Math115.SmallEntrySwitching.all_donor_small_entry_count_refined
#print axioms Math115.SmallEntrySwitching.all_donor_small_entry_count
#print axioms Math115.SmallEntrySwitching.all_donor_small_entry_probability_refined
#print axioms Math115.SmallEntrySwitching.all_donor_small_entry_probability
#print axioms Math115.SmallEntryTail.shiftEquiv
#print axioms Math115.SmallEntryTail.shiftPositiveEquiv
#print axioms Math115.SmallEntryTail.survival_step
#print axioms Math115.SmallEntryTail.survival_step_real
#print axioms Math115.SmallEntryTail.small_card_add_survival
#print axioms Math115.SmallEntryTail.all_donor_small_entry_count_strong
#print axioms Math115.SmallEntryTail.all_donor_small_entry_probability_strong
#print axioms Math115.SmallEntryTail.all_donor_survival_product_count
#print axioms Math115.SmallEntryTail.all_donor_small_entry_probability_product
#print axioms Math115.SmallEntryTail.survival_sum_le_entry_sum
#print axioms Math115.SmallEntryTail.all_donor_entry_sum_lower
#print axioms Math115.SmallEntryTail.all_donor_entry_mean_lower
#print axioms Math115.SurvivalAlgebra.nat_lower_tail_linear_bound
#print axioms Math115.SurvivalAlgebra.nat_survival_product_bound
#print axioms Math115.SurvivalAlgebra.nat_mean_tail_sum_bound

-- Scale arithmetic and the actual successful-unpadding count.
#print axioms Math115.DenseScaleConditions.width_bounds
#print axioms Math115.proposed_dense_scales
#print axioms Math115.proposed_padding_scales
#print axioms Math115.sharper_enlarged_margin_padding_scales
#print axioms Math115.shape_aware_linear_tail_budget
#print axioms Math115.shape_aware_linear_unpadding_error_le_half
#print axioms Math115.PaddedMarginBridge.marked_incident_margins
#print axioms Math115.PaddedMarginBridge.large_padding_good_card
#print axioms Math115.PaddedMarginBridge.enlarged_bad_count
#print axioms Math115.PaddedMarginBridge.sharper_padded_count_le_twice_original
#print axioms Math115.PaddedMarginBridge.enlarged_bad_count_strong
#print axioms Math115.PaddedMarginBridge.shape_aware_padded_count_le_twice_original

-- Literal physical leaf energy, hard limits, and global adjacent contrasts.
#print axioms Math115.PhysicalLeafEnergy.leafEnergySum_eq_physicalLeafEnergy
#print axioms Math115.PhysicalLeafEnergy.physicalLeafEnergy_tendsto
#print axioms Math115.PhysicalLeafEnergy.leafEnergySum_truncate_eq
#print axioms Math115.PhysicalLeafEnergy.physicalLeafEdges_subset
#print axioms Math115.PhysicalLeafEnergy.physicalLeafEdges_owner_unique
#print axioms Math115.PhysicalLeafEnergy.owner_unique
#print axioms Math115.PhysicalLeafEnergy.ownerEdges_pairwiseDisjoint
#print axioms Math115.PhysicalLeafEnergy.sum_ownerEnergy_le_physicalEnergy
#print axioms Math115.PhysicalLeafEnergy.sum_ownerEnergy_hardMarginal_le
#print axioms Math115.PhysicalLeafEnergy.leafEnergySum_tendsto
#print axioms Math115.PhysicalLeafEnergy.integer_root_leaf_transport_quarter_limit
#print axioms Math115.PhysicalLeafEnergy.integer_box_root_leaf_transport_quarter_limit
#print axioms Math115.PhysicalLeafEnergy.context_box_leaf_transport_quarter
#print axioms Math115.PhysicalLeafEnergy.repaired_root_transport_quarter
#print axioms Math115.PhysicalLeafEnergy.adjacent_physical_leaf_transport_quarter
#print axioms Math115.PhysicalLeafEnergy.ownerContrast_le_ownerEnergy
#print axioms Math115.PhysicalLeafEnergy.sum_ownerContrast_le_physicalEnergy

-- Sharper path variance, including hard zeros.
#print axioms Math115.PathDistanceSum.sum_values_eq_triangle
#print axioms Math115.PathDistanceSum.sum_dist_eq_two_triangles
#print axioms Math115.PathDistanceSum.sum_dist_eq_triangle_sub
#print axioms Math115.PathDistanceSum.sum_dist_le_triangle
#print axioms Math115.PathVariance.pathEnergy_nonneg
#print axioms Math115.PathVariance.weighted_pair_path_bound
#print axioms Math115.PathVariance.centered_at_mode_term
#print axioms Math115.PathVariance.weighted_path_variance_mode
#print axioms Math115.PathVariance.weighted_path_variance_mode_sharp
#print axioms Math115.PathVariance.weighted_path_variance_bound
#print axioms Math115.PathVariance.weighted_path_variance_of_adjacent
#print axioms Math115.PathVariance.child_variance_path_bound
#print axioms Math115.PathVariance.child_variance_limit_path_bound

-- Exact exposure telescoping and actual physical transversal.
#print axioms Math115.PhysicalExposureVariance.variance_eq_sum_prefixContribution
#print axioms Math115.PhysicalExposureVariance.canonical_context_variance_le_contrasts
#print axioms Math115.PhysicalExposureVariance.canonical_eliminate_eq_word_fibre
#print axioms Math115.PhysicalExposureVariance.word_context_variance_le_ownerContrasts
#print axioms Math115.PhysicalExposureVariance.prefixContribution_le_ownerContrasts
#print axioms Math115.PhysicalExposureVariance.variance_le_sum_ownerContrasts
#print axioms Math115.PhysicalExposureVariance.physical_transversal_variance_localized

-- Full physical variance, including actual defect repair.
#print axioms Math115.PhysicalFullVariance.physical_full_variance_localized
#print axioms Math115.PhysicalFullVariance.physical_variance_localized

-- Sequential ordinary-table padding and exact rational envelope.
#print axioms Math115.PaddingGrowthAlgebra.envelope_eq
#print axioms Math115.PaddingGrowthAlgebra.envelope_step
#print axioms Math115.PaddingGrowthAlgebra.one_add_pow_le_envelope
#print axioms Math115.PaddingGrowthAlgebra.envelope_32_div_47
#print axioms Math115.PaddingGrowthAlgebra.envelope_le_10147_div_5123
#print axioms Math115.PaddingGrowthAlgebra.one_add_pow_le_10147_div_5123
#print axioms Math115.PaddingGrowthAlgebra.one_add_pow_lt_two
#print axioms Math115.PaddingGrowthAlgebra.count_le_twice_of_growth
#print axioms Math115.PaddingGrowth.one_unit_count_growth
#print axioms Math115.PaddingGrowth.one_cell_count_growth
#print axioms Math115.PaddingGrowth.largePadding_insert
#print axioms Math115.PaddingGrowth.paddedRows_insert
#print axioms Math115.PaddingGrowth.paddedColumns_insert
#print axioms Math115.PaddingGrowth.large_padding_count_growth
#print axioms Math115.PaddingGrowth.large_padding_count_eq_of_zero_donors
#print axioms Math115.PaddingGrowth.sequential_scale_budget
#print axioms Math115.PaddingGrowth.sequential_padded_count_le_twice_original
#print axioms Math115.PaddingGrowth.sequential_shape_scale_budget
#print axioms Math115.PaddingGrowth.sequential_shape_padded_count_le_twice_original

-- Actual completion adjustments and degenerate geometry.
#print axioms Math115.CompletionAdjustment.elementary_star_bounds
#print axioms Math115.CompletionAdjustment.elementary_star_reverse_bounds
#print axioms Math115.CompletionAdjustment.exchange_selected_sum_abs_le_one
#print axioms Math115.CompletionAdjustment.exchange_residual_margins_one
#print axioms Math115.CompletionAdjustment.exchange_reference_adjustment_bounds
#print axioms Math115.CompletionAdjustment.repair_residual_formula
#print axioms Math115.CompletionAdjustment.repair_reference_adjustment_bounds
#print axioms Math115.CompletionAdjustment.row_major_repair_conditional
#print axioms Math115.CompletionAdjustment.repaired_profile_prefix
#print axioms Math115.CompletionAdjustment.translation_rejection_iff
#print axioms Math115.CompletionAdjustment.singleton_translation_nonnegative
#print axioms Math115.CompletionAdjustment.empty_rectangle_card_one
#print axioms Math115.CompletionAdjustment.physical_empty_completion_weight
#print axioms Math115.CompletionAdjustment.repair_reference_elementary
#print axioms Math115.CompletionAdjustment.repair_reverse_reference_adjustment_bounds

-- Actual edge acceptance with a free padding parameter.
#print axioms Math115.ReferenceEdgeAcceptance.zero_entry_count
#print axioms Math115.ReferenceEdgeAcceptance.rejected_card_eq_zero_union
#print axioms Math115.ReferenceEdgeAcceptance.rejected_count
#print axioms Math115.ReferenceEdgeAcceptance.rejected_count_le_two
#print axioms Math115.ReferenceEdgeAcceptance.rejected_add_accepted
#print axioms Math115.ReferenceEdgeAcceptance.rejection_probability_le
#print axioms Math115.ReferenceEdgeAcceptance.accepted_half_count
#print axioms Math115.ReferenceEdgeAcceptance.betweenAcceptedEquiv
#print axioms Math115.ReferenceEdgeAcceptance.singleton_between_accepted_card
#print axioms Math115.ReferenceEdgeAcceptance.between_accepted_half_count
#print axioms Math115.ReferenceEdgeAcceptance.designated_repair_adjustment_bounds
#print axioms Math115.ReferenceEdgeAcceptance.physical_reference_adjustment_bounds
#print axioms Math115.ReferenceEdgeAcceptance.reference_edge_acceptance_reduced

-- Actual original reference chain and polynomial comparison.
#print axioms Math115.SmallChainGap.fullConstant_le_polynomial
#print axioms Math115.SmallChainGap.smallProposal_localized_budget
#print axioms Math115.SmallChainGap.chain_poincare_localized
#print axioms Math115.SmallChainGap.paper_state_variance_localized
#print axioms Math115.SmallChainGap.paperSmallChain_poincare_exact
#print axioms Math115.SmallChainGap.paperSmallChain_poincare_d85

-- Actual original all-small unit chain.
#print axioms Math115.SmallChainGap.unitSmallChain_poincare_exact
#print axioms Math115.SmallChainGap.unitSmallChain_poincare_d85

-- Actual reduced ideal completion chain and d^25 specialization.
#print axioms Math115.ReducedSmallChain.chain
#print axioms Math115.ReducedSmallChain.chain_pi
#print axioms Math115.ReducedSmallChain.state_variance_localized
#print axioms Math115.ReducedSmallChain.nonreference_product_le_allowance
#print axioms Math115.ReducedSmallChain.chain_energy_lower
#print axioms Math115.ReducedSmallChain.chain_poincare_exact
#print axioms Math115.ReducedSmallChain.chain_poincare_polynomial
#print axioms Math115.ReducedSmallChain.reducedChain
#print axioms Math115.ReducedSmallChain.reducedChain_poincare_d25

-- ReducedAllSmallChain: checkpoint 4 additions.
#print axioms Math115.ReducedAllSmallChain.unitChain
#print axioms Math115.ReducedAllSmallChain.weight_eq_one
#print axioms Math115.ReducedAllSmallChain.unitChain_pi
#print axioms Math115.ReducedAllSmallChain.unitChain_pi_weight
#print axioms Math115.ReducedAllSmallChain.graphEnergy_empty
#print axioms Math115.ReducedAllSmallChain.unitChain_energy
#print axioms Math115.ReducedAllSmallChain.unitChain_poincare_exact
#print axioms Math115.ReducedAllSmallChain.unitChain_poincare_polynomial
#print axioms Math115.ReducedAllSmallChain.missing_reference_empty
#print axioms Math115.ReducedAllSmallChain.selectedChain
#print axioms Math115.ReducedAllSmallChain.selectedChain_pi
#print axioms Math115.ReducedAllSmallChain.selectedChain_poincare_exact
#print axioms Math115.ReducedAllSmallChain.selectedChain_poincare_polynomial
#print axioms Math115.ReducedAllSmallChain.reducedUnitChain
#print axioms Math115.ReducedAllSmallChain.reducedUnitChain_poincare_d25
#print axioms Math115.ReducedAllSmallChain.reducedSelectedChain
#print axioms Math115.ReducedAllSmallChain.reducedSelectedChain_poincare_d25

-- RepairVarianceRefinement: checkpoint 4 additions.
#print axioms Math115.RepairVarianceRefinement.square_repair_young
#print axioms Math115.RepairVarianceRefinement.repair_sqrt_coefficient_nonnegative
#print axioms Math115.RepairVarianceRefinement.repair_sqrt_coefficient_le_source
#print axioms Math115.RepairVarianceRefinement.repair_sqrt_coefficient_le_triangle
#print axioms Math115.RepairVarianceRefinement.variance_sum_repair_young
#print axioms Math115.RepairVarianceRefinement.variance_sum_repair_sqrt
#print axioms Math115.RepairVarianceRefinement.variance_repaired_energy_sqrt

-- PhysicalStateNonempty: checkpoint 4 additions.
#print axioms Math115.PhysicalStateNonempty.paddedTable
#print axioms Math115.PhysicalStateNonempty.small_entry_le
#print axioms Math115.PhysicalStateNonempty.states_nonempty_of_table
#print axioms Math115.PhysicalStateNonempty.states_nonempty
#print axioms Math115.PhysicalStateNonempty.feasibleReducedChain
#print axioms Math115.PhysicalStateNonempty.feasibleReducedChain_pi
#print axioms Math115.PhysicalStateNonempty.feasibleReducedChain_poincare_d25

-- IdealOracleScales: checkpoint 4 additions.
#print axioms Math115.IdealOracleScales.idealL
#print axioms Math115.IdealOracleScales.idealU
#print axioms Math115.IdealOracleScales.threshold_at_least_two
#print axioms Math115.IdealOracleScales.padding_at_least_three_dimension
#print axioms Math115.IdealOracleScales.threshold_at_least_twice_padding
#print axioms Math115.IdealOracleScales.sequential_scale_budget
#print axioms Math115.IdealOracleScales.padded_count_le_twice_original
#print axioms Math115.IdealOracleScales.padded_count_le_twice_successful
#print axioms Math115.IdealOracleScales.dense_padding_lower_bound
#print axioms Math115.IdealOracleScales.incompatible_dense_scales
#print axioms Math115.IdealOracleScales.dimension_at_least_eleven
#print axioms Math115.IdealOracleScales.cutoff
#print axioms Math115.IdealOracleScales.padding
#print axioms Math115.IdealOracleScales.IdealStates
#print axioms Math115.IdealOracleScales.idealLarge
#print axioms Math115.IdealOracleScales.ideal_large_padded_count_le_twice_original
#print axioms Math115.IdealOracleScales.referenceChain
#print axioms Math115.IdealOracleScales.referenceChain_poincare_d17
#print axioms Math115.IdealOracleScales.selectedChain
#print axioms Math115.IdealOracleScales.selectedChain_poincare_d17
#print axioms Math115.IdealOracleScales.feasibleChain
#print axioms Math115.IdealOracleScales.feasibleChain_poincare_d17

-- PhysicalRepairRefinement: checkpoint 4 additions.
#print axioms Math115.PhysicalRepairRefinement.refinedConstant
#print axioms Math115.PhysicalRepairRefinement.refinedConstant_nonnegative
#print axioms Math115.PhysicalRepairRefinement.refinedConstant_le_fullConstant
#print axioms Math115.PhysicalRepairRefinement.sqrt_coefficient_le_young
#print axioms Math115.PhysicalRepairRefinement.refinedConstant_le_polynomial
#print axioms Math115.PhysicalRepairRefinement.refinedProposal_budget
#print axioms Math115.PhysicalRepairRefinement.refinedReferenceProposal_budget
#print axioms Math115.PhysicalRepairRefinement.physical_full_variance_refined
#print axioms Math115.PhysicalRepairRefinement.physical_variance_refined
#print axioms Math115.PhysicalRepairRefinement.state_variance_refined
#print axioms Math115.PhysicalRepairRefinement.chain_poincare_exact_refined
#print axioms Math115.PhysicalRepairRefinement.unitChain_poincare_exact_refined
#print axioms Math115.PhysicalRepairRefinement.selectedChain_poincare_exact_refined
#print axioms Math115.PhysicalRepairRefinement.dimension_at_least_eleven
#print axioms Math115.PhysicalRepairRefinement.chain_poincare_polynomial_refined
#print axioms Math115.PhysicalRepairRefinement.unitChain_poincare_polynomial_refined
#print axioms Math115.PhysicalRepairRefinement.selectedChain_poincare_polynomial_refined

-- IdealRepairRefinement: checkpoint 4 additions.
#print axioms Math115.IdealRepairRefinement.referenceChain_poincare_d17_refined
#print axioms Math115.IdealRepairRefinement.selectedChain_poincare_d17_refined
#print axioms Math115.IdealRepairRefinement.feasibleChain_poincare_d17_refined
#print axioms Math115.IdealRepairRefinement.unitChain_poincare_d17_refined

-- ReducedRepairRefinement: checkpoint 4 additions.
#print axioms Math115.ReducedRepairRefinement.reducedChain_poincare_d25_refined
#print axioms Math115.ReducedRepairRefinement.reducedUnitChain_poincare_d25_refined
#print axioms Math115.ReducedRepairRefinement.reducedSelectedChain_poincare_d25_refined
#print axioms Math115.ReducedRepairRefinement.feasibleReducedChain_poincare_d25_refined

-- PhysicalStationaryMass: checkpoint 5 stationary output additions.
#print axioms Math115.PhysicalStationaryMass.physical_mass_eq_profiles
#print axioms Math115.PhysicalStationaryMass.physical_mass_eq_words_defects
#print axioms Math115.PhysicalStationaryMass.defect_mass_le_words
#print axioms Math115.PhysicalStationaryMass.normalizer
#print axioms Math115.PhysicalStationaryMass.normalizer_le_padded_count
#print axioms Math115.PhysicalStationaryMass.normalizer_le_original_count
#print axioms Math115.PhysicalStationaryMass.normalizer_positive
#print axioms Math115.PhysicalStationaryMass.success_ratio_lower

-- PhysicalStationarySuccess: checkpoint 5 stationary output additions.
#print axioms Math115.PhysicalStationarySuccess.paddedTable_small_rows
#print axioms Math115.PhysicalStationarySuccess.paddedTable_small_columns
#print axioms Math115.PhysicalStationarySuccess.originalJoint
#print axioms Math115.PhysicalStationarySuccess.originalJoint_projection
#print axioms Math115.PhysicalStationarySuccess.large_padding_rows
#print axioms Math115.PhysicalStationarySuccess.large_padding_columns
#print axioms Math115.PhysicalStationarySuccess.large
#print axioms Math115.PhysicalStationarySuccess.jointTable
#print axioms Math115.PhysicalStationarySuccess.originalSuccessfulJoint
#print axioms Math115.PhysicalStationarySuccess.unpadSuccessfulJoint
#print axioms Math115.PhysicalStationarySuccess.unpadSuccessfulJoint_val
#print axioms Math115.PhysicalStationarySuccess.successfulJointEquiv
#print axioms Math115.PhysicalStationarySuccess.stateJointProjection
#print axioms Math115.PhysicalStationarySuccess.stateJointProjection_injective
#print axioms Math115.PhysicalStationarySuccess.jointState
#print axioms Math115.PhysicalStationarySuccess.jointEmbedding
#print axioms Math115.PhysicalStationarySuccess.jointEmbedding_injective
#print axioms Math115.PhysicalStationarySuccess.jointEmbedding_balanced
#print axioms Math115.PhysicalStationarySuccess.balancedJointFromState
#print axioms Math115.PhysicalStationarySuccess.balancedJointFromState_projection
#print axioms Math115.PhysicalStationarySuccess.embedding_fromState
#print axioms Math115.PhysicalStationarySuccess.fromState_embedding
#print axioms Math115.PhysicalStationarySuccess.StateJointSuccess
#print axioms Math115.PhysicalStationarySuccess.successStateEquiv
#print axioms Math115.PhysicalStationarySuccess.originalStateSuccessEquiv

-- PhysicalStationaryLaw: checkpoint 5 stationary output additions.
#print axioms Math115.PhysicalStationaryLaw.fibre_card_weight
#print axioms Math115.PhysicalStationaryLaw.fibreNonempty
#print axioms Math115.PhysicalStationaryLaw.stateJoint_card
#print axioms Math115.PhysicalStationaryLaw.stationaryRat
#print axioms Math115.PhysicalStationaryLaw.stationaryRat_cast
#print axioms Math115.PhysicalStationaryLaw.stationaryLaw
#print axioms Math115.PhysicalStationaryLaw.jointLaw
#print axioms Math115.PhysicalStationaryLaw.jointLaw_uniform
#print axioms Math115.PhysicalStationaryLaw.stationary_trial_mass
#print axioms Math115.PhysicalStationaryLaw.stationary_trial_mass_real
#print axioms Math115.PhysicalStationaryLaw.stationary_failure_mass
#print axioms Math115.PhysicalStationaryLaw.stationary_success_probability
#print axioms Math115.PhysicalStationaryLaw.stationary_success_lower
#print axioms Math115.PhysicalStationaryLaw.stationary_success_probability_lower
#print axioms Math115.PhysicalStationaryLaw.stationary_retry_mass
#print axioms Math115.PhysicalStationaryLaw.stationary_retry_variation
#print axioms Math115.PhysicalStationaryLaw.ideal_padded_count
#print axioms Math115.PhysicalStationaryLaw.ideal_stationary_success_lower
#print axioms Math115.PhysicalStationaryLaw.ideal_stationary_success_probability_lower
#print axioms Math115.PhysicalStationaryLaw.ideal_stationary_retry_variation

#print axioms Math115.PhysicalRationalKernel.proposalRat
#print axioms Math115.PhysicalRationalKernel.proposalRat_cast
#print axioms Math115.PhysicalRationalKernel.lawOfCast
#print axioms Math115.PhysicalRationalKernel.referenceMoveRat
#print axioms Math115.PhysicalRationalKernel.referenceTransitionRat
#print axioms Math115.PhysicalRationalKernel.referenceMoveRat_cast
#print axioms Math115.PhysicalRationalKernel.referenceTransitionRat_cast
#print axioms Math115.PhysicalRationalKernel.referenceTransitionLaw
#print axioms Math115.PhysicalRationalKernel.unitMoveRat
#print axioms Math115.PhysicalRationalKernel.unitTransitionRat
#print axioms Math115.PhysicalRationalKernel.unitMoveRat_cast
#print axioms Math115.PhysicalRationalKernel.unitTransitionRat_cast
#print axioms Math115.PhysicalRationalKernel.unitTransitionLaw
#print axioms Math115.PhysicalRationalKernel.selectedTransitionLaw
#print axioms Math115.PhysicalRationalKernel.selectedTransitionLaw_cast
#print axioms Math115.PhysicalRationalKernel.selectedWalkLaw
#print axioms Math115.PhysicalRationalKernel.selectedWalkLaw_cast
#print axioms Math115.PhysicalFiniteWalk.capacityBound
#print axioms Math115.PhysicalFiniteWalk.massAllowance
#print axioms Math115.PhysicalFiniteWalk.massAllowance_positive
#print axioms Math115.PhysicalFiniteWalk.capacity_le_bound
#print axioms Math115.PhysicalFiniteWalk.weight_at_least_one
#print axioms Math115.PhysicalFiniteWalk.total_mass_le
#print axioms Math115.PhysicalFiniteWalk.selectedChain_pi_lower
#print axioms Math115.PhysicalFiniteWalk.selectedWalkLaw_variation
#print axioms Math115.PhysicalFiniteWalk.walkJointLaw
#print axioms Math115.PhysicalFiniteWalk.walkJointLaw_variation_le
#print axioms Math115.PhysicalFiniteWalk.walkJointLaw_variation
#print axioms Math115.PhysicalFiniteWalk.outerLaw
#print axioms Math115.PhysicalFiniteWalk.outerLaw_variation
#print axioms Math115.PhysicalFiniteWalk.initialState
#print axioms Math115.PhysicalFiniteWalk.idealGapAllowance
#print axioms Math115.PhysicalFiniteWalk.idealGapAllowance_at_least_one
#print axioms Math115.PhysicalFiniteWalk.successAllowance
#print axioms Math115.PhysicalFiniteWalk.successAllowance_positive
#print axioms Math115.PhysicalFiniteWalk.idealOuterLaw
#print axioms Math115.PhysicalFiniteWalk.idealOuterLaw_variation
#print axioms Math115.PhysicalFiniteWalk.exp_neg_steps_le_inverse
#print axioms Math115.PhysicalFiniteWalk.idealOuterLaw_variation_of_log_schedule

-- Checkpoint 7: actual and approximate completion oracle laws.
#print axioms Math115.PhysicalCompletionOracle.mapLaw_constant
#print axioms Math115.PhysicalCompletionOracle.completionStep_variation_thinned
#print axioms Math115.PhysicalCompletionOracle.equivLaw_uniform
#print axioms Math115.PhysicalCompletionOracle.proposalRat_nonnegative
#print axioms Math115.PhysicalCompletionOracle.proposalAllowance
#print axioms Math115.PhysicalCompletionOracle.proposalAllowance_nonnegative
#print axioms Math115.PhysicalCompletionOracle.proposalAllowance_le_half
#print axioms Math115.PhysicalCompletionOracle.degree
#print axioms Math115.PhysicalCompletionOracle.degree_le
#print axioms Math115.PhysicalCompletionOracle.proposalWeight_nonnegative
#print axioms Math115.PhysicalCompletionOracle.proposalWeight_total
#print axioms Math115.PhysicalCompletionOracle.proposalWeight_total_le_allowance
#print axioms Math115.PhysicalCompletionOracle.proposalWeight_total_le_one
#print axioms Math115.PhysicalCompletionOracle.physicalProposalLaw
#print axioms Math115.PhysicalCompletionOracle.ReferenceTable
#print axioms Math115.PhysicalCompletionOracle.referenceTableNonempty
#print axioms Math115.PhysicalCompletionOracle.referenceStepLaw
#print axioms Math115.PhysicalCompletionOracle.referenceExactStep_eq
#print axioms Math115.PhysicalCompletionOracle.referenceStep_variation_local
#print axioms Math115.PhysicalCompletionOracle.referenceStep_variation_uniform
#print axioms Math115.PhysicalCompletionOracle.referenceFibreMap
#print axioms Math115.PhysicalCompletionOracle.referenceCompletionLaw
#print axioms Math115.PhysicalCompletionOracle.referenceCompletionLaw_variation
#print axioms Math115.PhysicalCompletionOracle.OracleFamily
#print axioms Math115.PhysicalCompletionOracle.selectedStepLaw
#print axioms Math115.PhysicalCompletionOracle.selectedCompletionLaw
#print axioms Math115.PhysicalCompletionOracle.selectedStepLaw_variation
#print axioms Math115.PhysicalCompletionOracle.selectedCompletionLaw_variation
#print axioms Math115.PhysicalCompletionOracle.empty_fibre_card_one
#print axioms Math115.PhysicalApproximateOracle.approximateJointLaw
#print axioms Math115.PhysicalApproximateOracle.approximateJointLaw_variation
#print axioms Math115.PhysicalApproximateOracle.approximateOuterLaw
#print axioms Math115.PhysicalApproximateOracle.approximateOuterLaw_variation_le
#print axioms Math115.PhysicalApproximateOracle.approximateOuterLaw_variation
#print axioms Math115.PhysicalApproximateOracle.idealOracleOuterLaw
#print axioms Math115.PhysicalApproximateOracle.idealOracleOuterLaw_variation
#print axioms Math115.PhysicalApproximateOracle.approximateOuterLaw_variation_of_budget

-- Checkpoint 7: exact integer lattice codec core.
#print axioms Math115.LatticeCompletion.Array
#print axioms Math115.LatticeCompletion.difference
#print axioms Math115.LatticeCompletion.prefixSum
#print axioms Math115.LatticeCompletion.ZeroAxes
#print axioms Math115.LatticeCompletion.ZeroBoundary
#print axioms Math115.LatticeCompletion.BoundedDigits
#print axioms Math115.LatticeCompletion.difference_row_sum
#print axioms Math115.LatticeCompletion.difference_column_sum
#print axioms Math115.LatticeCompletion.difference_row_sum_zero
#print axioms Math115.LatticeCompletion.difference_column_sum_zero
#print axioms Math115.LatticeCompletion.prefix_zero_axes
#print axioms Math115.LatticeCompletion.prefix_difference
#print axioms Math115.LatticeCompletion.difference_prefix
#print axioms Math115.LatticeCompletion.difference_bounds
#print axioms Math115.LatticeCompletion.encode
#print axioms Math115.LatticeCompletion.decode
#print axioms Math115.LatticeCompletion.residue
#print axioms Math115.LatticeCompletion.prefix_encode
#print axioms Math115.LatticeCompletion.scaled_digit_ediv
#print axioms Math115.LatticeCompletion.scaled_digit_emod
#print axioms Math115.LatticeCompletion.decode_encode
#print axioms Math115.LatticeCompletion.residue_encode
#print axioms Math115.LatticeCompletion.residue_zero_axes
#print axioms Math115.LatticeCompletion.residue_bounded
#print axioms Math115.LatticeCompletion.encode_decode
#print axioms Math115.LatticeCompletion.encode_entry_at_least_two
#print axioms Math115.LatticeCompletion.encode_row_margin
#print axioms Math115.LatticeCompletion.encode_column_margin
#print axioms Math115.LatticeCompletion.residue_zero_boundary_of_divisible_margins
#print axioms Math115.LatticeCompletion.decode_row_margin
#print axioms Math115.LatticeCompletion.decode_column_margin
#print axioms Math115.LatticeCompletion.accepted_fine_entry_at_least_two
#print axioms Math115.LatticeCompletion.OffsetDigits
#print axioms Math115.LatticeCompletion.codecEquiv
#print axioms Math115.LatticeCompletion.FiniteDigits
#print axioms Math115.LatticeCompletion.finiteOffsets
#print axioms Math115.LatticeCompletion.finiteOffsets_zero_boundary
#print axioms Math115.LatticeCompletion.finiteOffsets_bounded
#print axioms Math115.LatticeCompletion.finite_encode_decode
#print axioms Math115.LatticeCompletion.finiteOffsets_apply
#print axioms Math115.LatticeCompletion.finiteOffsets_injective
#print axioms Math115.LatticeCompletion.finiteEncode_injective
#print axioms Math115.LatticeCompletion.finiteDigits_card
#print axioms Math115.LatticeCompletion.encodedFamily_card

-- Checkpoint 7: actual dilated completion margins.
#print axioms Math115.DilatedCompletionMargins.rowLargeCount_rectangle
#print axioms Math115.DilatedCompletionMargins.columnLargeCount_rectangle
#print axioms Math115.DilatedCompletionMargins.total_large_cell_count
#print axioms Math115.DilatedCompletionMargins.physical_residual_row_lower
#print axioms Math115.DilatedCompletionMargins.physical_residual_column_lower
#print axioms Math115.DilatedCompletionMargins.reference_row_lower
#print axioms Math115.DilatedCompletionMargins.reference_column_lower
#print axioms Math115.DilatedCompletionMargins.reference_row_total_eq_residual
#print axioms Math115.DilatedCompletionMargins.reference_total_upper
#print axioms Math115.DilatedCompletionMargins.fineRows
#print axioms Math115.DilatedCompletionMargins.fineColumns
#print axioms Math115.DilatedCompletionMargins.FineReferenceTable
#print axioms Math115.DilatedCompletionMargins.fine_row_total
#print axioms Math115.DilatedCompletionMargins.fine_column_total
#print axioms Math115.DilatedCompletionMargins.fine_totals
#print axioms Math115.DilatedCompletionMargins.fineReferenceTableNonempty
#print axioms Math115.DilatedCompletionMargins.fine_total_upper
#print axioms Math115.DilatedCompletionMargins.fine_row_dense_minimum
#print axioms Math115.DilatedCompletionMargins.fine_column_dense_minimum
#print axioms Math115.DilatedCompletionMargins.ideal_reference_row_geometric_minimum
#print axioms Math115.DilatedCompletionMargins.ideal_reference_column_geometric_minimum

-- Checkpoint 8: LatticeCompletionFinite.
#print axioms Math115.LatticeCompletionFinite.Grid
#print axioms Math115.LatticeCompletionFinite.extend
#print axioms Math115.LatticeCompletionFinite.restrict
#print axioms Math115.LatticeCompletionFinite.extend_inside
#print axioms Math115.LatticeCompletionFinite.extend_outside
#print axioms Math115.LatticeCompletionFinite.extend_injective
#print axioms Math115.LatticeCompletionFinite.range_sum_extend_row
#print axioms Math115.LatticeCompletionFinite.range_sum_extend_column
#print axioms Math115.LatticeCompletionFinite.offsets_difference_outside
#print axioms Math115.LatticeCompletionFinite.encodeGrid
#print axioms Math115.LatticeCompletionFinite.decodeGrid
#print axioms Math115.LatticeCompletionFinite.extend_encodeGrid
#print axioms Math115.LatticeCompletionFinite.fine_row_divisible
#print axioms Math115.LatticeCompletionFinite.fine_column_divisible
#print axioms Math115.LatticeCompletionFinite.fine_residue_zero_strips
#print axioms Math115.LatticeCompletionFinite.recoveredDigits
#print axioms Math115.LatticeCompletionFinite.recoveredDigits_val
#print axioms Math115.LatticeCompletionFinite.residue_eq_finiteOffsets
#print axioms Math115.LatticeCompletionFinite.extend_decodeGrid
#print axioms Math115.LatticeCompletionFinite.decodeGrid_encodeGrid
#print axioms Math115.LatticeCompletionFinite.recoveredDigits_encodeGrid
#print axioms Math115.LatticeCompletionFinite.encodeGrid_decodeGrid
#print axioms Math115.LatticeCompletionFinite.encodeGrid_row
#print axioms Math115.LatticeCompletionFinite.encodeGrid_column
#print axioms Math115.LatticeCompletionFinite.encodeGrid_nonneg
#print axioms Math115.LatticeCompletionFinite.decodeGrid_row
#print axioms Math115.LatticeCompletionFinite.decodeGrid_column
#print axioms Math115.LatticeCompletionFinite.intGrid
#print axioms Math115.LatticeCompletionFinite.natGrid
#print axioms Math115.LatticeCompletionFinite.natGrid_intGrid
#print axioms Math115.LatticeCompletionFinite.intGrid_natGrid
#print axioms Math115.LatticeCompletionFinite.intGrid_row
#print axioms Math115.LatticeCompletionFinite.intGrid_column
#print axioms Math115.LatticeCompletionFinite.natGrid_hasMargins
#print axioms Math115.LatticeCompletionFinite.fineMargin
#print axioms Math115.LatticeCompletionFinite.FineTable
#print axioms Math115.LatticeCompletionFinite.fineTable_row_divisible
#print axioms Math115.LatticeCompletionFinite.fineTable_column_divisible
#print axioms Math115.LatticeCompletionFinite.Accepted
#print axioms Math115.LatticeCompletionFinite.AcceptedFine
#print axioms Math115.LatticeCompletionFinite.encodeTable
#print axioms Math115.LatticeCompletionFinite.intGrid_encodeTable
#print axioms Math115.LatticeCompletionFinite.encodeTable_accepted
#print axioms Math115.LatticeCompletionFinite.encodeAccepted
#print axioms Math115.LatticeCompletionFinite.decodeAccepted
#print axioms Math115.LatticeCompletionFinite.intGrid_decodeAccepted
#print axioms Math115.LatticeCompletionFinite.decodeAccepted_encodeAccepted
#print axioms Math115.LatticeCompletionFinite.encodeAccepted_decodeAccepted
#print axioms Math115.LatticeCompletionFinite.acceptedEquiv
#print axioms Math115.LatticeCompletionFinite.accepted_card
#print axioms Math115.LatticeCompletionFinite.fixedFiberEquiv
#print axioms Math115.LatticeCompletionFinite.fixedFiber_card

-- Checkpoint 8: LatticeCellVolume.
#print axioms Math115.LatticeCellVolume.prefixCell
#print axioms Math115.LatticeCellVolume.prefixCell_measurable
#print axioms Math115.LatticeCellVolume.mem_prefixCell_iff
#print axioms Math115.LatticeCellVolume.floor_mul_eq_anchor
#print axioms Math115.LatticeCellVolume.prefixCell_disjoint
#print axioms Math115.LatticeCellVolume.prefixCell_volume
#print axioms Math115.LatticeCellVolume.prefixCells_measurable
#print axioms Math115.LatticeCellVolume.prefixCells_pairwiseDisjoint
#print axioms Math115.LatticeCellVolume.prefix_lattice_cells_volume
#print axioms Math115.LatticeCellVolume.prefix_unit_cells_volume
#print axioms Math115.LatticeCellVolume.prefix_lattice_cells_volume_ne_top
#print axioms Math115.LatticeCellVolume.prefix_lattice_cells_volume_pos
#print axioms Math115.LatticeCellVolume.prefix_lattice_cells_volume_toReal
#print axioms Math115.LatticeCellVolume.prefixCell_error
#print axioms Math115.LatticeCellVolume.mixed_difference_error
#print axioms Math115.LatticeCellVolume.volume_image_translate
#print axioms Math115.LatticeCellVolume.volume_image_scale
#print axioms Math115.LatticeCellVolume.volume_le_of_translated_subset
#print axioms Math115.LatticeCellVolume.volume_le_of_subset_scaled_translate

-- Checkpoint 8: CompletionRetryBudget.
#print axioms Math115.CompletionRetryBudget.uniform_success_mass
#print axioms Math115.CompletionRetryBudget.uniform_success_mass_of_card
#print axioms Math115.CompletionRetryBudget.failure_nonnegative
#print axioms Math115.CompletionRetryBudget.success_nonnegative
#print axioms Math115.CompletionRetryBudget.failure_le_one
#print axioms Math115.CompletionRetryBudget.equal_success_normalized
#print axioms Math115.CompletionRetryBudget.equal_success_retry_mass
#print axioms Math115.CompletionRetryBudget.equal_success_retry_variation
#print axioms Math115.CompletionRetryBudget.approximate_retry_variation
#print axioms Math115.CompletionRetryBudget.approximate_retry_variation_of_success
#print axioms Math115.CompletionRetryBudget.dyadic
#print axioms Math115.CompletionRetryBudget.retries
#print axioms Math115.CompletionRetryBudget.finePrecision
#print axioms Math115.CompletionRetryBudget.retries_positive
#print axioms Math115.CompletionRetryBudget.dyadic_positive
#print axioms Math115.CompletionRetryBudget.dyadic_succ
#print axioms Math115.CompletionRetryBudget.dyadic_antitone_step
#print axioms Math115.CompletionRetryBudget.geometric_budget
#print axioms Math115.CompletionRetryBudget.fine_draw_budget
#print axioms Math115.CompletionRetryBudget.retry_budget
#print axioms Math115.CompletionRetryBudget.retry_budget_target
#print axioms Math115.CompletionRetryBudget.completion_retry_variation_half
#print axioms Math115.CompletionRetryBudget.completion_retry_variation

-- Checkpoint 8: LatticeCompletionLaw.
#print axioms Math115.LatticeCompletionLaw.trial
#print axioms Math115.LatticeCompletionLaw.trial_eq_none
#print axioms Math115.LatticeCompletionLaw.successfulFiberEquiv
#print axioms Math115.LatticeCompletionLaw.successfulFiber_card
#print axioms Math115.LatticeCompletionLaw.fine_nonempty_of_fallback
#print axioms Math115.LatticeCompletionLaw.ideal_success_mass
#print axioms Math115.LatticeCompletionLaw.ideal_success_probability
#print axioms Math115.LatticeCompletionLaw.ideal_retry_mass
#print axioms Math115.LatticeCompletionLaw.approximate_retry_bound
#print axioms Math115.LatticeCompletionLaw.completion_accuracy_half
#print axioms Math115.LatticeCompletionLaw.completion_accuracy

-- Checkpoint 8: PrefixTransportation.
#print axioms Math115.PrefixTransportation.Array
#print axioms Math115.PrefixTransportation.Matrix
#print axioms Math115.PrefixTransportation.Interior
#print axioms Math115.PrefixTransportation.difference
#print axioms Math115.PrefixTransportation.prefixSum
#print axioms Math115.PrefixTransportation.ZeroAxes
#print axioms Math115.PrefixTransportation.ZeroBoundary
#print axioms Math115.PrefixTransportation.difference_row_sum
#print axioms Math115.PrefixTransportation.difference_column_sum
#print axioms Math115.PrefixTransportation.difference_row_sum_zero
#print axioms Math115.PrefixTransportation.difference_column_sum_zero
#print axioms Math115.PrefixTransportation.prefix_zero_axes
#print axioms Math115.PrefixTransportation.prefix_difference
#print axioms Math115.PrefixTransportation.difference_prefix
#print axioms Math115.PrefixTransportation.extend
#print axioms Math115.PrefixTransportation.restrict
#print axioms Math115.PrefixTransportation.extend_inside
#print axioms Math115.PrefixTransportation.extend_outside
#print axioms Math115.PrefixTransportation.range_sum_extend_row
#print axioms Math115.PrefixTransportation.range_sum_extend_column
#print axioms Math115.PrefixTransportation.interiorPrefix
#print axioms Math115.PrefixTransportation.interiorPrefix_add
#print axioms Math115.PrefixTransportation.interiorPrefix_smul
#print axioms Math115.PrefixTransportation.interiorPrefix_injective_of_margins
#print axioms Math115.PrefixTransportation.offsets
#print axioms Math115.PrefixTransportation.offsets_zero_boundary
#print axioms Math115.PrefixTransportation.offsets_apply
#print axioms Math115.PrefixTransportation.offsets_difference_outside
#print axioms Math115.PrefixTransportation.perturbation
#print axioms Math115.PrefixTransportation.extend_perturbation
#print axioms Math115.PrefixTransportation.perturbation_rows_zero
#print axioms Math115.PrefixTransportation.perturbation_columns_zero
#print axioms Math115.PrefixTransportation.interiorPrefix_perturbation
#print axioms Math115.PrefixTransportation.offsets_error
#print axioms Math115.PrefixTransportation.perturbation_error
#print axioms Math115.PrefixTransportation.Feasible
#print axioms Math115.PrefixTransportation.PrefixRegion
#print axioms Math115.PrefixTransportation.feasible_add
#print axioms Math115.PrefixTransportation.feasible_smul
#print axioms Math115.PrefixTransportation.feasible_const
#print axioms Math115.PrefixTransportation.prefixRegion_translate_subset
#print axioms Math115.PrefixTransportation.prefixRegion_volume_mono_of_difference_table
#print axioms Math115.PrefixTransportation.prefixRegion_constant_translate_subset
#print axioms Math115.PrefixTransportation.exists_feasible_of_nonnegative_equal_total
#print axioms Math115.PrefixTransportation.prefixRegion_volume_mono
#print axioms Math115.PrefixTransportation.prefixRegion_scale_eq
#print axioms Math115.PrefixTransportation.prefixRegion_volume_scale
#print axioms Math115.PrefixTransportation.prefix_error_upper_containment

-- Checkpoint 8: PrefixFloorCover.
#print axioms Math115.PrefixFloorCover.floorPrefix
#print axioms Math115.PrefixFloorCover.floorGrid
#print axioms Math115.PrefixFloorCover.floorPrefix_zero_axes
#print axioms Math115.PrefixFloorCover.floorGrid_entry_error
#print axioms Math115.PrefixFloorCover.floorGrid_nonnegative
#print axioms Math115.PrefixFloorCover.marginPrefix
#print axioms Math115.PrefixFloorCover.prefix_full_columns
#print axioms Math115.PrefixFloorCover.prefix_full_rows
#print axioms Math115.PrefixFloorCover.marginPrefix_succ
#print axioms Math115.PrefixFloorCover.floorGrid_rows
#print axioms Math115.PrefixFloorCover.floorGrid_columns
#print axioms Math115.PrefixFloorCover.roundedTable
#print axioms Math115.PrefixFloorCover.tableAnchor
#print axioms Math115.PrefixFloorCover.tableReal
#print axioms Math115.PrefixFloorCover.tableAnchor_cast
#print axioms Math115.PrefixFloorCover.tableReal_feasible
#print axioms Math115.PrefixFloorCover.tableAnchor_injective
#print axioms Math115.PrefixFloorCover.floorGrid_prefix
#print axioms Math115.PrefixFloorCover.roundedTable_anchor
#print axioms Math115.PrefixFloorCover.interiorPrefix_mem_rounded_cell
#print axioms Math115.PrefixFloorCover.lower_floor_cover
#print axioms Math115.PrefixFloorCover.lower_volume_le_card

-- Checkpoint 8: CompletionCountBound.
#print axioms Math115.CompletionCountBound.fineCells
#print axioms Math115.CompletionCountBound.normalized_fine_feasible
#print axioms Math115.CompletionCountBound.upper_cell_cover
#print axioms Math115.CompletionCountBound.fine_cells_volume
#print axioms Math115.CompletionCountBound.fine_cells_volume_toReal
#print axioms Math115.CompletionCountBound.fine_cells_volume_le_upper
#print axioms Math115.CompletionCountBound.inflation
#print axioms Math115.CompletionCountBound.inflation_pos
#print axioms Math115.CompletionCountBound.inflation_ge_one
#print axioms Math115.CompletionCountBound.inflated_margin_ge_upper
#print axioms Math115.CompletionCountBound.shifted_totals_equal
#print axioms Math115.CompletionCountBound.reduced_totals_equal
#print axioms Math115.CompletionCountBound.upper_volume_le_inflated_lower
#print axioms Math115.CompletionCountBound.fine_cells_volume_le_count
#print axioms Math115.CompletionCountBound.fine_card_le
#print axioms Math115.CompletionCountBound.fine_nat_card_le

-- Checkpoint 8: CompletionAcceptance.
#print axioms Math115.CompletionAcceptance.two_mul_le_power_twelve
#print axioms Math115.CompletionAcceptance.dilationFactor
#print axioms Math115.CompletionAcceptance.increment
#print axioms Math115.CompletionAcceptance.denominator_positive
#print axioms Math115.CompletionAcceptance.dilationFactor_eq_one_add
#print axioms Math115.CompletionAcceptance.increment_nonnegative
#print axioms Math115.CompletionAcceptance.dilationFactor_positive
#print axioms Math115.CompletionAcceptance.two_div_k_le_inverse_d
#print axioms Math115.CompletionAcceptance.exponent_allowance
#print axioms Math115.CompletionAcceptance.exp_four_thirds_lt_four
#print axioms Math115.CompletionAcceptance.dilationFactor_pow_lt_four
#print axioms Math115.CompletionAcceptance.acceptance_lower_real
#print axioms Math115.CompletionAcceptance.acceptance_lower_rat

-- Checkpoint 8: LatticeCompletionAccuracy.
#print axioms Math115.LatticeCompletionAccuracy.inflation_three_d
#print axioms Math115.LatticeCompletionAccuracy.ideal_acceptance_quarter
#print axioms Math115.LatticeCompletionAccuracy.originalUniform
#print axioms Math115.LatticeCompletionAccuracy.fineUniform
#print axioms Math115.LatticeCompletionAccuracy.completion_accuracy_half
#print axioms Math115.LatticeCompletionAccuracy.completion_accuracy
#print axioms Math115.LatticeCompletionAccuracy.chosen_dilation_acceptance_quarter
#print axioms Math115.LatticeCompletionAccuracy.chosen_dilation_accuracy
